---
#####################
# DATABASE
- name: installs mongodb 3.2.20, makes it listen to 0.0.0.0 and starts+enables it
  hosts: default
  become: true

  tasks:
  - name: add the GPG key for mongoDB 3.2
    apt_key:
      url: https://www.mongodb.org/static/pgp/server-3.2.asc
      state: present

  - name: create a /etc/apt/sources.list.d/mongodb-org-3.2.list file
    copy:
      dest: "/etc/apt/sources.list.d/mongodb-org-3.2.list"
      content: |
        deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse

  - name: install mongodb 3.2.20
    apt:
      name:
      - mongodb-org=3.2.20
      - mongodb-org-server=3.2.20
      - mongodb-org-mongos=3.2.20
      - mongodb-org-tools=3.2.20
      state: present
      update_cache: yes

  - name: change the bind ip in /etc/mongod.conf
    replace:
      path: /etc/mongod.conf
      regexp: '^(  bindIp: 127.0.0.1)$'
      replace: '  bindIp: 0.0.0.0'

  - name: enable and start mongod
    systemd:
      name: mongod
      state: started
      enabled: yes